### ISSUE TITLE
Tap release not working correctly

### ISSUE THREAD

**Issue by theofidry** [box-project/homebrew-box#2]
Although new releases are being tagged and PHARs published it doesn't look like the Tap release is updating this repository.

Could this be due to the published artefact being uploaded after the tag?

Any idea @pierredup?

**Comment by pierredup** [comment]
Looking at the code for tap-release, it tries to get the artefact immediately when a tag is created. So uploading the artefact afterwards indeed won't trigger the update.

**Comment by theofidry** [comment]
is there anyway to fix that? I doubt I can change the workflow on Box side, maybe there is a hook we could trigger for tap-release

**Comment by theofidry** [comment]
Opened https://github.com/toolmantim/tap-release/issues/67

**Comment by KEINOS** [comment]
Sorry, I didn't notice this issue and did a manual update PR #3 to the latest version ...

Nothing better than automated. Please drop the PR #3 if any plan to update after fixing this issue.

**Comment by theofidry** [comment]
The homebrew tap should now be updated automatically
